# Generated by Django 4.0.2 on 2022-02-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0002_rename_text_entry_tex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='tex',
            new_name='text',
        ),
    ]
