# Generated by Django 4.0.2 on 2022-02-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0003_rename_tex_entry_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='preview',
        ),
    ]
