# Generated by Django 4.0.2 on 2022-02-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0004_remove_entry_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='preview',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
