# Generated by Django 4.0.2 on 2022-02-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0005_entry_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='preview',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
