# Generated by Django 4.0.2 on 2022-02-13 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0006_alter_entry_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
