# Generated by Django 4.0.2 on 2022-02-13 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0007_entry_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='publication_date',
            new_name='last_edit_date',
        ),
    ]
