# Generated by Django 4.0.2 on 2022-02-13 21:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0008_rename_publication_date_entry_last_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
