# Generated by Django 4.0.2 on 2022-02-17 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0013_alter_entry_last_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_edit_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 0, 25, 4, 701427, tzinfo=utc)),
        ),
    ]
