# Generated by Django 4.0.2 on 2022-02-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0017_alter_checkin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateTimeField(default=17),
        ),
    ]
