# Generated by Django 4.0.2 on 2022-02-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0024_alter_checkin_date_alter_entry_last_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_edit_date',
            field=models.DateTimeField(),
        ),
    ]
