# Generated by Django 4.0.2 on 2022-02-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0025_alter_entry_last_edit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='score',
            field=models.FloatField(),
        ),
    ]
