# Generated by Django 3.1.2 on 2022-02-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0026_alter_checkin_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='depression_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
