# Generated by Django 3.1.2 on 2022-03-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0027_auto_20220228_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='depression_score',
        ),
        migrations.AddField(
            model_name='entry',
            name='depression',
            field=models.BooleanField(default=False),
        ),
    ]
