# Generated by Django 3.1.2 on 2022-03-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalhealth', '0028_auto_20220228_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
    ]
